#!/bin/sh
set -e
#--------------------------------------------------------------------
# Suppression des fichiers de PlumePg du répertoire des
# extensions de Postgresql
#
# Désinstaller une version supprimera aussi les fichiers des
# versions antérieures.
#--------------------------------------------------------------------

# Nom de l'extension
EXT_NAME=#EXT_NAME#

# Itération sur l'ensenmble des versions de PostgreSQL gérées
for version in 10 11 12 13 14 15; do
  # L'emplacement des extensions est dépendant de la version de Postgresql
  PG_EXT_DIR=/usr/share/postgresql/$version/extension
  if [ -d $PG_EXT_DIR ]; then
    rm -f $PG_EXT_DIR/$EXT_NAME.control
    rm -f $PG_EXT_DIR/$EXT_NAME--*.sql
  fi
done
